packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - esbuild

catalog:
  typescript: ^5.8.3
  vitest: ^3.2.4
  zod: ^4.4.3
  ajv: ^8.17.1
  ajv-formats: ^3.0.1
  jose: ^6.0.10
  esbuild: ^0.25.5
  playwright: ^1.53.0
